In [24]:
import numpy as np
import pandas as pd
# from nltk.stem.snowball import SnowballStemmer
# import pymorphy2
import time
from textblob import TextBlob
df_train_short_1400 = pd.read_csv("Source/df_train_short_1400.csv")
df_train_short_1400_1600 = pd.read_csv("Source/df_train_short_1400_1600.csv")

In [25]:
df_train_short_1400_1600

,Unnamed: 0,CLIENT_ID,RETRO_DT,tokens,urls_hashed
0,1400,5949459,20200926,"['smartfon', '3', 'креди', '2', 'работ', '1', ...",ae964ea7904692e8264a2232061121a3 3 38a59efe2ce...
1,1401,1124059,20210309,"['ради', '2', 'серге', '1', 'сторон', '1', 'оп...",83e85bee0d81c0e9e5047e202cddf534 10 aee71c8d18...
2,1402,1903651,20210922,"['выплат', '1', 'отказо', '3', 'forge', '2', '...",f333f7c2bc75e8eac24efe906c54f1be 1 7b0185606d5...
3,1403,1482263,20210609,"['креди', '2', 'банковск', '1', 'новы', '2', '...",346312e420798e35cd6d136e86a6e204 1 59e180a243e...
4,1404,1123935,20210309,"['входящи', '1', 'recover', '1', 'почт', '1', ...",7405aaece8dbd9b744b0752a7ecae526 1 197d57e77f6...
...,...,...,...,...,...
195,1595,1807042,20210826,"['задач', '4']",6bfc846093307cc7bb8daaf05f9dc390 4
196,1596,811869491,20211012,"['звонкам', '2', 'мобильны', '4', 'снят', '2',...",83e85bee0d81c0e9e5047e202cddf534 2 8a41ca31446...
197,1597,5868610,20200829,"['выплат', '9', 'concep', '1', 'forge', '3', '...",83e85bee0d81c0e9e5047e202cddf534 2 9dfa3995ca3...
198,1598,5280045,20200307,"['феврал', '1', 'стать', '1', 'malefisen', '1'...",aee71c8d18d6b91b36bf599208a91777 63 abf79a01fb...
199,1599,5475864,20200421,"['prazdnovan', '1', 'носи', '1', 'кров', '1', ...",de6b5f2f626d9b52483d56fdf245b8d7 1 28fe45133db...

In [26]:
df_train_short_1600 = pd.concat([df_train_short_1400, df_train_short_1400_1600], axis = 0)

In [27]:
df_train_short_1600

,Unnamed: 0,CLIENT_ID,RETRO_DT,tokens,urls_hashed
0,0,5909886,20200911,"['форм', '1', 'мачех', '1', 'работ', '1', 'пас...",7bbcc146c0ba4df814701ff7297b2205 1 ee0d49cbc99...
1,1,1385448,20210519,"['платиз', '1', 'мобильны', '2', 'серг', '1', ...",1889e0cbd3e343e9521a07aa312257ac 2 8253d8d3a67...
2,2,1866195,20210913,"['симс', '3', 'креди', '1', 'язык', '1', 'разл...",6e617b4bfdbef85d8b09ec08ac72f0f2 1 94309f5f116...
3,3,1587081,20210702,"['code', '1', 'истори', '1', 'сцф', '1', 'шаг'...",1e833434273e04ba76cfcfb4b48ad21b 3 aee71c8d18d...
4,4,1400908,20210522,"['отказо', '2', 'товар', '1', 'серге', '1', 'к...",83e85bee0d81c0e9e5047e202cddf534 3 6e617b4bfdb...
...,...,...,...,...,...
195,1595,1807042,20210826,"['задач', '4']",6bfc846093307cc7bb8daaf05f9dc390 4
196,1596,811869491,20211012,"['звонкам', '2', 'мобильны', '4', 'снят', '2',...",83e85bee0d81c0e9e5047e202cddf534 2 8a41ca31446...
197,1597,5868610,20200829,"['выплат', '9', 'concep', '1', 'forge', '3', '...",83e85bee0d81c0e9e5047e202cddf534 2 9dfa3995ca3...
198,1598,5280045,20200307,"['феврал', '1', 'стать', '1', 'malefisen', '1'...",aee71c8d18d6b91b36bf599208a91777 63 abf79a01fb...
199,1599,5475864,20200421,"['prazdnovan', '1', 'носи', '1', 'кров', '1', ...",de6b5f2f626d9b52483d56fdf245b8d7 1 28fe45133db...

In [28]:
df_train_short_1600.to_csv("Source/df_train_short_1600.csv", index = False)